controller_joint_names: ['', 'front_left_wheel_joint', 'front_right_wheel_joint', 'rear_left_wheel_joint', 'rear_right_wheel_joint', 'front_cam_mount_joint', 'front_cam_joint', 'rear_cam_mount_joint', 'rear_cam_joint', ]
